/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import org.junit.jupiter.api.Test;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.lang.reflect.Type;
import java.util.List;
import java.util.Random;

import static org.junit.jupiter.api.Assertions.*;

class Main {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void jsonFileTest() throws FileNotFoundException {
        Gson gson = new Gson();
        JsonReader reader = new JsonReader(new FileReader("C:\\Users\\STUDENT\\401class\\quotes\\recentquotes.json"));

        Type jsonCasting = new TypeToken<List<FromJson>>() {
        }.getType();

        List<FromJson> jsonList = gson.fromJson(reader, jsonCasting);

        Random random = new Random();
        int randoms = random.nextInt(jsonList.size());
        String test1 = jsonList.get(randoms).toString() ;
        assertEquals(test1,jsonList.get(randoms).toString());
    }
}
